"""Snapshot a web page into a committed markdown document.

Fetches an HTML page (notably Google Docs HTML exports, which need CSS-class
recovery for bold/italic and list nesting), converts it to markdown, and
rewrites the target file only when the content actually changed - the
snapshot date alone never causes a diff.

Used for keeping local copies of externally-owned reference docs (assembly
house constraints and the like) that agents need offline.

Usage:
  cs docs snapshot <url> <out.md> [--title ...] [--note ...]
"""

from __future__ import annotations

import datetime as dt
import re
import sys
import urllib.request
from html.parser import HTMLParser
from pathlib import Path
from urllib.parse import parse_qs, urlsplit

HEADER_TEMPLATE = """\
<!-- AUTO-GENERATED by `cs docs snapshot` - do not edit by hand.
     Source:   {url}
     Snapshot: {date} -->

# {title}

{note}

---

{body}"""

BLOCK_TAGS = ("h1", "h2", "h3", "h4", "h5", "h6", "p", "li")


def _unwrap_google_redirect(href: str) -> str:
    """Google Docs exports wrap every link in a google.com/url redirect."""
    parts = urlsplit(href)
    if parts.netloc.endswith("google.com") and parts.path == "/url":
        target = parse_qs(parts.query).get("q")
        if target:
            return target[0]
    return href


class SnapshotHTMLParser(HTMLParser):
    """Convert an HTML page (incl. Google Docs exports) into markdown blocks.

    Google Docs flattens nested lists into sibling <ul>/<ol> elements whose
    class carries the nesting level as a suffix (e.g. lst-kix_abc123-2), and
    encodes bold/italic in generated CSS classes rather than <b>/<i> tags, so
    both are recovered here.
    """

    def __init__(self) -> None:
        super().__init__()
        self.blocks: list[tuple[str, int, str]] = []  # (kind, list_level, text)
        self._in_style = False
        self._css_chunks: list[str] = []
        self._bold_classes: set[str] = set()
        self._italic_classes: set[str] = set()
        self._list_levels: list[int] = []
        self._block: str | None = None
        self._block_level = 0
        # runs: (text, bold, italic, href)
        self._runs: list[tuple[str, bool, bool, str | None]] = []
        self._span_stack: list[tuple[bool, bool]] = []
        self._link_stack: list[str] = []

    def _parse_css(self, css: str) -> None:
        for name, decls in re.findall(r"\.([-\w]+)\{([^}]*)\}", css):
            if "font-weight:700" in decls:
                self._bold_classes.add(name)
            if "font-style:italic" in decls:
                self._italic_classes.add(name)

    @staticmethod
    def _level_from_classes(classes: list[str]) -> int:
        for cls in classes:
            if cls.startswith("lst-"):
                match = re.search(r"-(\d+)$", cls)
                if match:
                    return int(match.group(1))
        return 0

    def _open_block(self, kind: str) -> None:
        self._flush()
        self._block = kind
        self._block_level = self._list_levels[-1] if kind == "li" and self._list_levels else 0
        self._runs = []

    def _flush(self) -> None:
        if self._block is None:
            return
        text = self._render_runs()
        if text:
            self.blocks.append((self._block, self._block_level, text))
        self._block = None
        self._runs = []

    def _render_runs(self) -> str:
        merged: list[list] = []
        for text, bold, italic, href in self._runs:
            if merged and merged[-1][1:] == [bold, italic, href]:
                merged[-1][0] += text
            else:
                merged.append([text, bold, italic, href])
        parts: list[str] = []
        for text, bold, italic, href in merged:
            text = re.sub(r"\s+", " ", text)
            core = text.strip()
            if not core:
                if text:
                    parts.append(" ")
                continue
            if bold and italic:
                core = f"***{core}***"
            elif bold:
                core = f"**{core}**"
            elif italic:
                core = f"*{core}*"
            if href:
                core = f"[{core}]({href})"
            lead = " " if text.startswith(" ") else ""
            trail = " " if text.endswith(" ") else ""
            parts.append(f"{lead}{core}{trail}")
        return re.sub(r" {2,}", " ", "".join(parts)).strip()

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        attr_map = dict(attrs)
        classes = (attr_map.get("class") or "").split()
        if tag == "style":
            self._in_style = True
        elif tag in ("ul", "ol"):
            self._list_levels.append(self._level_from_classes(classes))
        elif tag in BLOCK_TAGS:
            self._open_block(tag)
        elif tag == "span" and self._block is not None:
            bold = any(c in self._bold_classes for c in classes)
            italic = any(c in self._italic_classes for c in classes)
            self._span_stack.append((bold, italic))
        elif tag == "a" and self._block is not None:
            self._link_stack.append(_unwrap_google_redirect(attr_map.get("href", "")))
        elif tag == "br" and self._block is not None:
            self._runs.append((" ", False, False, None))

    def handle_endtag(self, tag: str) -> None:
        if tag == "style":
            self._in_style = False
            self._parse_css("".join(self._css_chunks))
        elif tag in ("ul", "ol"):
            if self._list_levels:
                self._list_levels.pop()
        elif tag in BLOCK_TAGS:
            self._flush()
        elif tag == "span":
            if self._span_stack:
                self._span_stack.pop()
        elif tag == "a":
            if self._link_stack:
                self._link_stack.pop()

    def handle_data(self, data: str) -> None:
        if self._in_style:
            self._css_chunks.append(data)
            return
        if self._block is None or not data:
            return
        bold = any(b for b, _ in self._span_stack)
        italic = any(i for _, i in self._span_stack)
        href = self._link_stack[-1] if self._link_stack else None
        self._runs.append((data.replace("\xa0", " "), bold, italic, href))


def render_markdown(blocks: list[tuple[str, int, str]]) -> str:
    lines: list[str] = []
    prev_kind: str | None = None
    for kind, level, text in blocks:
        if lines and not (kind == "li" and prev_kind == "li"):
            lines.append("")
        if kind == "li":
            lines.append("  " * level + "- " + text)
        elif kind[0] == "h" and kind[1:].isdigit():
            lines.append("#" * int(kind[1:]) + " " + text)
        else:
            lines.append(text)
        prev_kind = kind
    return "\n".join(lines) + "\n"


def snapshot(url: str, out_path: Path, title: str = "", note: str = "") -> int:
    request = urllib.request.Request(url, headers={"User-Agent": "circuit-synth docs snapshot"})
    with urllib.request.urlopen(request, timeout=30) as response:
        html_text = response.read().decode("utf-8", errors="replace")

    parser = SnapshotHTMLParser()
    parser.feed(html_text)
    parser.close()

    # A real fetch yields dozens of blocks; refuse to overwrite the snapshot
    # with an error page or a drastically restructured document.
    if len(parser.blocks) < 10:
        print(
            f"error: parsed only {len(parser.blocks)} blocks from {url}; "
            "page layout may have changed - snapshot left untouched.",
            file=sys.stderr,
        )
        return 1

    body = render_markdown(parser.blocks)
    doc = HEADER_TEMPLATE.format(
        url=url,
        date=dt.date.today().isoformat(),
        title=title or f"Snapshot of {url}",
        note=note or f"A markdown snapshot of {url}.",
        body=body,
    )

    def stable(text: str) -> str:
        return re.sub(r"Snapshot: \d{4}-\d{2}-\d{2}", "Snapshot: <date>", text)

    out_path = Path(out_path)
    if out_path.exists() and stable(out_path.read_text()) == stable(doc):
        print(f"{out_path} is up to date (source unchanged).")
        return 0

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(doc)
    print(f"Updated {out_path} from {url}. Review the diff.")
    return 0
